---
- name: Update and K8 Host Nodes
  hosts: k8s_cluster
  tasks:
    - name: Update all APT packages
      become: yes
      apt:
        name: '*'
        state: latest
      when: ansible_os_family == "Debian"

    - name: Upgrade OS
      become: yes
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Truncate Nginx logs
      become: yes
      shell: sudo truncate -s 0 /var/log/nginx/access.log /var/log/nginx/error.log

    - name: Append to local file
      delegate_to: localhost
      lineinfile:
        path: "/mnt/QNAP/backuplogs/updates/updates.txt"
        line: "Last update on {{ inventory_hostname }}: {{ ansible_date_time.date }} {{ ansible_date_time.time }}"

- import_playbook: /home/ansible/playbooks/tasks/k8reboot.yml